# Generated by Django 5.1.1 on 2024-09-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseform',
            old_name='phon1',
            new_name='course',
        ),
    ]
